# CI Simulation Configuration Template
# This file defines the default configuration for the CI simulation tool

# Python versions to test against
python_versions:
  - "3.9"
  - "3.10"
  - "3.11"

# Global timeout settings (in seconds)
timeouts:
  default_check: 300
  test_execution: 600
  security_scan: 180
  performance_test: 900

# Check configurations
checks:
  code_quality:
    enabled: true
    auto_fix: false
    tools:
      black:
        enabled: true
        line_length: 88
      isort:
        enabled: true
        profile: "black"
      flake8:
        enabled: true
        max_line_length: 88
        ignore: ["E203", "W503"]
      mypy:
        enabled: true
        strict: false

  testing:
    enabled: true
    parallel: true
    coverage_threshold: 80
    test_types:
      - unit
      - integration
      - ai_compatibility
      - performance

  security:
    enabled: true
    tools:
      safety:
        enabled: true
        ignore_ids: []
      bandit:
        enabled: true
        severity_level: "medium"

  performance:
    enabled: true
    regression_threshold: 30.0  # percentage
    baseline_comparison: true

# AI component testing
ai_components:
  copilot:
    enabled: true
    test_demos: true
  cursor:
    enabled: true
    test_demos: true
  kiro:
    enabled: true
    test_demos: true

# Environment settings
environment:
  virtual_display: true
  qt_dependencies: true
  cleanup_after_run: true

# Report settings
reporting:
  formats:
    - markdown
    - json
  output_directory: "reports/ci-simulation"
  history_retention_days: 30
  include_suggestions: true

# Git integration
git:
  pre_commit_hook: false
  ignore_patterns:
    - "*.pyc"
    - "__pycache__/"
    - ".pytest_cache/"
    - "reports/ci-simulation/"
    - ".kiro/ci-history/"
    - "logs/ci-simulation.log"
