# CI/CD Simulation Configuration
# PhotoGeoView AI統合プロジェクト用

# Python versions to test
python_versions:
  - "3.9"
  - "3.10"
  - "3.11"

# Enabled checks
enabled_checks:
  - "code_quality"
  - "unit_tests"
  - "integration_tests"
  - "ai_compatibility"
  - "security_scan"
  - "performance_tests"

# Timeout settings (in seconds)
timeout_seconds: 1800  # 30 minutes for overall execution
check_timeout_seconds: 600  # 10 minutes per individual check
max_demo_timeout: 30  # 30 seconds per demo script

# Output configuration
output_directory: "reports/ci-simulation"
parallel_execution: false  # 並列実行を無効化
auto_fix: false
git_hook_enabled: false

# Performance thresholds
performance_threshold: 30.0  # 30% regression threshold

# AI components to test
ai_components:
  copilot: true
  cursor: true
  kiro: true

# Security settings
security_scan_enabled: true

# Report formats
report_formats:
  - "markdown"
  - "json"

# Directory structure
directories:
  history: ".kiro/ci-history"
  reports: "reports/ci-simulation"
  logs: "logs"
  temp: "temp/ci-simulation"

# Tool-specific configurations
tools:
  black:
    enabled: true
    line_length: 88
    target_version: ["py39", "py310", "py311"]
    timeout: 60

  isort:
    enabled: true
    profile: "black"
    multi_line_output: 3
    timeout: 60

  flake8:
    enabled: true
    max_line_length: 88
    ignore: ["E203", "W503", "F401", "E402"]
    timeout: 120

  mypy:
    enabled: true
    strict: true
    ignore_missing_imports: true
    timeout: 180

  safety:
    enabled: true
    ignore_ids: []
    timeout: 120

  bandit:
    enabled: true
    severity_level: "medium"
    timeout: 120

  pytest:
    enabled: true
    timeout: 300
    parallel: true
    max_workers: 4

# Resource management
max_parallel_tasks: 1  # 並列実行を無効化して順次実行
memory_threshold_percent: 80
cpu_threshold_percent: 90

# Verbosity and logging
verbose: false
quiet: false
log_level: "INFO"

# GitHub Actions integration
github_actions:
  enabled: true
  artifact_upload: true
  status_check: true
  timeout_minutes: 30
