name: Simple CI

on:
  push:
    branches: [ main, develop, ai-integration-main ]
  pull_request:
    branches: [ main, develop, ai-integration-main ]

jobs:
  ci-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[ci]

    - name: Run Simple CI
      run: |
        python tools/ci/simple_ci.py --format both

    - name: Upload CI Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ci-reports
        path: reports/
        retention-days: 30
